# Generated by Django 3.0.4 on 2020-11-12 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='* Campos obrigatórios', max_length=20, unique=True, verbose_name='Código da triagem *')),
                ('data', models.DateField(help_text='dd/mm/aaaa', verbose_name='Data da consulta *')),
                ('hora', models.TimeField(help_text='hh:mm', verbose_name='Hora da consulta *')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome Completo *')),
                ('idade', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Idade *')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Altura *')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Peso *')),
                ('imc', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='IMC *')),
                ('febre', models.BooleanField(verbose_name='Tem febre?')),
                ('dor_cabeca', models.BooleanField(verbose_name='Tem dor de cabeça?')),
                ('secrecao_espirro', models.BooleanField(verbose_name='Tem secreção nasal ou espirros?')),
                ('dor_garganta', models.BooleanField(verbose_name='Tem dor/irritação de garganta?')),
                ('tosse_seca', models.BooleanField(verbose_name='Tem tosse seca?')),
                ('dificuldade_respiratoria', models.BooleanField(verbose_name='Tem dificuldae respiratória?')),
                ('dores_corpo', models.BooleanField(verbose_name='Tem dores no corpo?')),
                ('diarreia', models.BooleanField(verbose_name='Tem diarreia?')),
                ('viagem_covid', models.BooleanField(verbose_name='Viajou, nos últimos 14 dias, para algum local com casos confirmados de COVID-19?')),
                ('contato_covid', models.BooleanField(verbose_name='Esteve em contato, nos últimos 14 dias, com um caso diagnosticado com COVID-19?')),
                ('resultado', models.BooleanField(verbose_name='Resultado')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'triagem',
                'verbose_name_plural': 'triagens',
                'ordering': ['-data', '-hora', 'nome'],
                'unique_together': {('codigo', 'data', 'hora')},
            },
        ),
    ]
