# Generated by Django 3.0.4 on 2020-11-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='dificuldade_respiratoria',
            field=models.BooleanField(verbose_name='Tem dificuldade respiratória?'),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='resultado',
            field=models.PositiveIntegerField(verbose_name='Resultado'),
        ),
    ]
